
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-24T10:00:58-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fe8fb9ec9071b929568417332de6e9b0292c259",
 "version": "2.0.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
